 CREATE TABLESPACE HOPITAL_TBS DATAFILE  'HOPITAL_TBS.dat'  SIZE 100M AUTOEXTEND ON  ONLINE;
  
 
 
CREATE TEMPORARY TABLESPACE HOPITAL_TempTBS TEMPFILE 'HOPITAL_TempTBS.dat' SIZE 100M  AUTOEXTEND ON;
